Main svc
facedolls/java-explore-with-me pull request #2
Opened 2024-07-02 13:44 UTC by facedolls

2024-07-03 21:10 UTC, andrew-larkin requested changes
Привет! Очень нравится работа - все сделано чисто и лаконично, с лучшими практиками. Одно исправление в docker-compose и очень рекомендую классы внутри папок распределить по новым папкам. потому что большое кол-во разных классов в одной папке - не очень удобно, они еще к разным вещам относятся.

2024-07-03 21:10 UTC, andrew-larkin commented on docker-compose.yml
> +    container_name: ewm-db-container
для БД добавляем также volumes

2024-07-04 13:18 UTC, facedolls commented on docker-compose.yml
> +    container_name: ewm-db-container
Поправил

2024-07-04 19:22 UTC, andrew-larkin approved these changes
Привет! Отлично, работа принята!

2024-07-05 13:40 UTC, merged